pull_request_rules:
  - name: Automatic merge for release PRs
    conditions:
      - "label=autorelease: pending"
      - base=main
      - -draft
      - -conflict
    actions:
      merge:
        method: squash
