queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - "label=autorelease: pending"
pull_request_rules:
  - name: Make sure PR are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      update:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label dependencies
    conditions:
      - label = dependencies
    actions:
      merge:
  - name: Automatic merge release PRs
    conditions:
      - "label=autorelease: pending"
    actions:
      merge:
        method: squash
      queue:
        name: default
