name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Install dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
